services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      system-network:
        ipv4_address: 15.10.0.10 
    restart: always
    volumes:
      - mongo-data:/data/db 
      - ./mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
    container_name: api-mongo
    command: bash -c "npm run dev"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo:27017/product
      - APP_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    networks:
      - system-network
    restart: always

  seed:
    build:
      context: .
    container_name: mongo-seed
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - system-network
    restart: "no"  
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/product
    entrypoint: ["./node_modules/.bin/ts-node", "src/database/seeds/seeds.ts"]

volumes:
  mongo-data:

networks:
  system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 15.10.0.0/24
